### ISSUE TITLE
设置字段不显示后，在页面“表格列控制”框中却还显示

### ISSUE THREAD

**Issue by zsf513** [erupts/erupt#107]
### 版本情况

JDK版本： openjdk_8_201   
erupt版本： 1.10.8

### 问题描述（包括截图）
代码中设置了“逻辑删除标识”delFlag不显示，但是在页面上的“表格列控制”选择框中还是有“逻辑删除标识”这个选项。

<img width="783" alt="image" src="https://user-images.githubusercontent.com/4221354/176125015-b02d6fa2-693e-4170-a112-905ec9f466b6.png">

<img width="1165" alt="image" src="https://user-images.githubusercontent.com/4221354/176125269-811cb44a-3e2c-42d2-af9a-f6415150eeb9.png">

**Comment by erupts** [comment]
如果不想让字段在表格展示不使用@View注解即可，而不是通过show来控制
