### ISSUE TITLE
错误提示对话框存在未执行i18n的情况

### ISSUE THREAD

**Issue by William-d-zk** [erupts/erupt#110]
### 版本情况

JDK版本：openjdk version "17.0.3" 2022-04-19 LTS   
erupt版本： 1.10.10 （请确保最新尝试是否还有问题）

### 问题描述（包括截图）
提示信息未延i18n进行正常翻译

![image](https://user-images.githubusercontent.com/8856002/181872215-395bb64d-2a12-466d-9cba-a33e1132c27e.png)

**Comment by erupts** [comment]
1.12.0及以上版本已对I18n做了全面增强
