### ISSUE TITLE
jdbc-template 与 JPA存在兼容问题

### ISSUE THREAD

**Issue by William-d-zk** [erupts/erupt#113]
### 版本情况

JDK版本： openjdk_17_03
erupt版本： 1.10.10

初始化执行时调用了spring boot - jdbc-template 
这部分与JPA 对 hibernate的配置定义存在冲突，hibernate 配置了default_schema时，建表语句会自动关联schema，但是
UpmsDataLoadService  line:52 开始调用的jdbc 无法正常执行，此处需统一使用jpa执行。

**Comment by erupts** [comment]
1.10.14版本UpmsDataLoadService类已使用JPA进行查询
