### ISSUE TITLE
希望开放  数据列表 行“操作”下的 update/delete/view的权限控制，允许开发人员根据数据列的内容动态控制“按钮”是否出现

### ISSUE THREAD

**Issue by zhiyish** [erupts/erupt#121]
### 版本情况

JDK版本： openjdk_8_201   
erupt版本： 1.10.13

### 问题描述（包括截图）
系统
![(6H)ZK3A30`D)8K@2IR8{{C](https://user-images.githubusercontent.com/64768255/189517571-29f77d1d-4e4d-410b-b8b2-f842e5413873.jpg)

根据每行数据的某列值控制 行操作的查看、修改、删除三个按钮是否显示
1、可用为”是“，就出现 删除和编辑
2、可用为”否“就不出现 删除和编辑

**Comment by erupts** [comment]
1.12.16版本已支持行按钮动态控制，详见：https://www.yuque.com/erupts/erupt/nicqg3#BPV07
