### ISSUE TITLE
切换TPL菜单不生效

### ISSUE THREAD

**Issue by dudiao** [erupts/erupt#126]
### 版本情况

JDK版本： zuul_11.0.14   
erupt版本： 1.10.14 （请确保最新尝试是否还有问题）

### 问题描述（包括截图）

1. 复现代码
配置两个菜单，名称和类型值分别为：

- 测试1 `amis.html?code=test1`
- 测试2 `amis.html?code=test2`

访问菜单时，访问测试1，页面正常，再访问测试2，地址栏有变化，但是页面没有刷新

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

**Comment by erupts** [comment]
使用通配符的方式解决：
@TplAction("amis.*.html")
或
@TplAction("/abc/**")
匹配规则同spring mvc
