### ISSUE TITLE
Mongodb默认排序不起作用

### ISSUE THREAD

**Issue by conway2019** [erupts/erupt#134]
### 版本情况

JDK版本： 1.8   
erupt版本： 1.10.12

### 问题描述（包括截图）
orderBy = "time desc"代码不起作用，显示的结果是monngodb的默认排序
以下截图没有按照时间进行排序。
![image](https://user-images.githubusercontent.com/59103289/210704609-4ff9b18b-b9f3-40fa-b4f7-dd559eae0eea.png)

### 复现代码
@EruptDataProcessor(EruptMongodbImpl.MONGODB_PROCESS)
@Document(collection = "qa_item")
@Erupt(name = "问答管理", 
	power = @Power(importable = true, export = true), 
	orderBy = "time desc")`
public class QA {
	@Id
	@EruptField
	private String id;

	@EruptField(
			views = @View(title = "时间", sortable = true), 
			edit = @Edit(title = "时间", search = @Search(vague = true))
	)
	private String time;

**Comment by erupts** [comment]
1.10.x版本已修复此问题
