### ISSUE TITLE
分布式下job行为异常

### ISSUE THREAD

**Issue by TinChiWay** [erupts/erupt#137]
### 版本情况

JDK版本： openjdk_8_201   
erupt版本： 1.10.X （请确保最新尝试是否还有问题）

### 问题描述（包括截图）
起了两个server A和B，两个node C和D
job在B上添加的并且在B上执行，我在A把job禁用了，B依然执行
另外在job执行时将B kill后，job的执行不能转移到其他节点，重启B后继续执行

这就又让我产生了疑惑，为什么要有ABCD这四个节点，项目中设立server和node的意义是什么

**Comment by erupts** [comment]
不支持分布式任务，erupt cloud存在的意义是分布式远程配置页面的管理，文档也未提及job的分布式能力
