### ISSUE TITLE
夜间模式导致首页不能正常显示、路由复用失效 

### ISSUE THREAD

**Issue by microlong666** [erupts/erupt#14]
### 版本情况

JDK版本：11.0.9.1
erupt版本：1.6.4

### 问题描述（包括截图）

- 开启夜间模式，路由复用被强制关闭

- 在夜间模式下开启路由复用，夜间模式失效（互相冲突）

- 夜间模式下首页一片漆黑，无法显示内容，移动端显示正常（若能提供夜间模式下自定义页面 **取消反转色选项** 更佳）

![首页不能正常显示](https://images.gitee.com/uploads/images/2021/0217/235256_db75fb0a_7568304.png "微信图片_20210217235142.png")

![冲突](https://images.gitee.com/uploads/images/2021/0217/235503_4ead05ad_7568304.png "微信图片_20210217235440.png")

![移动端首页正常](https://images.gitee.com/uploads/images/2021/0218/000512_24964d6b_7568304.png "微信图片_20210218000451.png")

1. 复现代码

``` html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1" name="viewport">
</head>
<body>
  <h1>Hello World</h1>
</body>
</html>
```

2. 测试涉及到的文件： `home.html`

**Comment by erupts** [comment]
黑夜模式的原理是 css的filter属性配置了页面全局反色，但在chrome浏览器中存在bug，在相对定位情况下，反色会使容器变形，Safari就无此问题，暂无解决办法，路由复用也是暗黑模式引起的，我故意做了互斥操作

**Comment by microlong666** [comment]
好的谢谢
