### ISSUE TITLE
用户表格排序错误问题

### ISSUE THREAD

**Issue by Lyon1994** [erupts/erupt#146]
### 版本情况

JDK版本： openjdk_8_201   
erupt版本： 1.11.2 （请确保最新尝试是否还有问题）

### 问题描述（包括截图）
在“系统管理>用户配置”页面中，创建了12个用户，之后查询时排序的第一页和第二页不正确

***第一页数据截图:***
![image](https://user-images.githubusercontent.com/8456652/224873832-5d8bc596-1e23-498d-b41d-552abcb1b82e.png)

×××第二页数据截图：***
![image](https://user-images.githubusercontent.com/8456652/224873895-26754e60-64f1-4f80-9699-23fc974d27da.png)

1. 复现代码
    无，官方库中的错误

2. 堆栈信息
    无，官方库中的错误

4. 测试涉及到的文件（注意脱密）
    无，官方库中的错误

**Comment by erupts** [comment]
使用的什么数据库？

**Comment by Lyon1994** [comment]
> 

使用的是postgresql数据库，版本为15

**Comment by erupts** [comment]
可能与postgresql的排序方式有关，不增加order by，普通的查询sql查询顺序是否有问题？
