### ISSUE TITLE
请问自定义按钮如何跳转到自定义页面？不想做弹出层

### ISSUE THREAD

**Issue by ChangJinLong** [erupts/erupt#168]
### 版本情况

JDK版本： openjdk_8_201   
erupt版本： 1.11.7 
### 想法
希望通过配置自定义按钮时可以选择跳转《自定义页面》还是弹出层，这样自定按钮的可玩性就更高了
🤔或者现有的功能下有什么其他的解决方案吗

**Comment by ChangJinLong** [comment]
还有一个疑问就是每次点击自定义按钮都会有一个确认弹窗，请问有什么方法或参数可以不用每次都弹窗吗

**Comment by erupts** [comment]
暂不支持自定义按钮确认弹窗的是否开启配置
