### ISSUE TITLE
1.12.0 默认查询条件未写入组件值

### ISSUE THREAD

**Issue by fawn-deer** [erupts/erupt#180]
### 版本情况

JDK版本： openjdk_11
erupt版本： 1.11.3 -> 1.12.0

### 问题描述（包括截图）

dataproxy中的默认查询条件, web

1.11.3
![{SJCNN_87TN K)1 WXVK7%H](https://github.com/erupts/erupt/assets/23301284/3a73ada6-2b62-4a89-8d6f-01001b22011f)

1.12.0
![4P2%2TKRVH B6W33{(K(WFG](https://github.com/erupts/erupt/assets/23301284/2928c024-39d8-45ab-aef5-bdb19ae17334)

注: 两个图片中的条件配置一致, 文字可忽略

1.12版本中, 返回数据中已经有查询条件, 但web组件没刷新, 查询请求中也没有

### 修复意见

web中的查询组件设置返回的值

**Comment by fawn-deer** [comment]
补一个dataproxy的代码
``` java
    @Override
    public void searchCondition(Map<String, Object> condition) {
        condition.put("createTime", List.of(DateUtil.today() + " 00:00:00", DateUtil.today() + " 23:59:59"));
    }
```

**Comment by erupts** [comment]
可升级到1.12.3版本，已针对该问题做出修复
