### ISSUE TITLE
希望在Search 条件里面支持默认search选项

### ISSUE THREAD

**Issue by supercat188** [erupts/erupt#188]
### 版本情况

JDK版本： openjdk_8_201   
erupt版本： 1.12.1（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
希望在Search 条件里面支持默认search选项，这样可以减少一次鼠标点选。

**Comment by erupts** [comment]
升级到1.12.3版本，使用dataProxy的searchCondition方法可实现默认查询条件能力
详见：https://www.yuque.com/erupts/erupt/nicqg3
