### ISSUE TITLE
水印不是全屏展示

### ISSUE THREAD

**Issue by chenxiaolong8023** [erupts/erupt#189]
### 版本情况

JDK版本： openjdk_8_201   
erupt版本： 1.12.0（请确保最新尝试是否还有问题）

### 问题描述（包括截图）

仅红色区域有水印，是否可以全页面都有水印

![image](https://github.com/erupts/erupt/assets/33304073/57239da0-655c-4ea6-8452-7c68118fbe52)

**Comment by erupts** [comment]
1.12.7 及以上版本已处理此样式问题
