### ISSUE TITLE
定时任务的日志能否改为可配置项，或者单独设置是否需要输出日志

### ISSUE THREAD

**Issue by thewen99** [erupts/erupt#192]
### 版本情况

我现在的定时任务几乎都是每秒执行的，每天都会输出大量的日志，其实这些日志对我并没有用，而且会让我在查询我需要看的日志的时候查询速度变的非常慢

**Comment by erupts** [comment]
好的，下个版本增加 Job 颗粒度是否写入日志的配置

**Comment by erupts** [comment]
1.12.10版本已支持该能力，可在每条任务中定义是否记录日志
