### ISSUE TITLE
模版下载报错

### ISSUE THREAD

**Issue by supercat188** [erupts/erupt#193]
### 版本情况

JDK版本： openjdk_8_201   
erupt版本： 1.12.2 （请确保最新尝试是否还有问题）

### 问题描述（包括截图）
模版下载报错
经分析，是导出模版的excel下拉框选项超过了255个字符。对于关联到erupt对象的字段，或者下拉菜单字段，如果选项很多，就会有这个问题。
String literals in formulas can't be bigger than 255 characters ASCII
1. 复现代码
```java
@Erupt(name="xxx")
public class Test{

}
```

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

**Comment by erupts** [comment]
这是excel下拉框项长度的限制，建议做适当裁剪
