### ISSUE TITLE
请问一下drill的数据表里怎么获取来源数据

### ISSUE THREAD

**Issue by dqsdhr** [erupts/erupt#196]
### 版本情况

JDK版本： openjdk_1.8.0_372  
erupt版本： 1.12.2 

### 问题描述（包括截图）
从数据表A类里drill到B类里，创建新数据时，想把关联的字段自动填充到drill的类里。这个有什么好的办法实现么。

**Comment by erupts** [comment]
自动填充的，只要在注解中标记依赖字段即可，如果想获取关联字段的值可以注入 request对象通过请求头的方式获取
