### ISSUE TITLE
1.12.2升级1.12.3版本发生下钻drill数据异常的问题

### ISSUE THREAD

**Issue by dqsdhr** [erupts/erupt#198]
### 版本情况

JDK版本： openjdk_8_201   
erupt版本： 1.12.3 （请确保最新尝试是否还有问题）

### 问题描述（包括截图）
代码从1.12.2升级到1.12.3后，发现所有下钻的数据都不能过滤对应的id了。

**Comment by aazainn** [comment]
+1，我也刚好遇到这个问题。
复现的话，直接看demo项目就可以了：https://www.erupt.xyz/demo/#/build/table/EruptJob
下钻的结果都一样

**Comment by erupts** [comment]
1.12.4版本已针对此问题紧急修复
