### ISSUE TITLE
erupt 自带框架的id序列生成，不同环境dev sit uat 数据迁移会冲突

### ISSUE THREAD

**Issue by supercat188** [erupts/erupt#240]
### 版本情况

JDK版本： openjdk_8_201   
erupt版本： 所有版本

### 问题描述（包括截图）

erupt 自带框架的序列生成，应用成熟之后，体量会变大，不同环境dev sit uat 做组织，用户迁移的时候非常不方便，容易冲突和串号。能否改为输入一个id来作为主键，这样不同环境迁移就非常方便。

**Comment by erupts** [comment]
下面几种方式可以参考
- 不继承BaseModel在主键列增加@EruptFIeld → @Edit 注解即可，在页面中编辑主键
- 可以使用UUID作为主键
- 在dataProxy中beforeAdd写主键列写入自定义ID值
