### ISSUE TITLE
操作中的自定义按钮  可否支持文字

### ISSUE THREAD

**Issue by zhongren** [erupts/erupt#246]
### 版本情况

JDK版本： openjdk_8_201   
erupt版本： 1.X.X （请确保最新尝试是否还有问题）

### 问题描述（包括截图）

![1](https://github.com/erupts/erupt/assets/7368043/3b0a52d1-3641-4327-9b3e-e9fd3d647dca)
![2](https://github.com/erupts/erupt/assets/7368043/fab2bfa5-6014-4980-98a1-d2bc8ae6f028)
能否支持按钮文字

**Comment by erupts** [comment]
1.12.17版本已支持按钮折叠配置，可显示文字，将icon配置为空字符串也可显示文本
