### ISSUE TITLE
请求参数带 code 直接登录

### ISSUE THREAD

**Issue by bravet** [erupts/erupt#248]
### 版本情况

JDK版本： openjdk_17 
erupt版本： 1.12.12

### 问题描述（包括截图）
刚开始试用，发现一个问题，不确定是哪里配置问题还是安全问题。请求带上 code=xxx（任意值）即可绕过登录？

1. 复现代码

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

**Comment by erupts** [comment]
没有遇到过，具体怎么操作的？

**Comment by erupts** [comment]
非BUG，在得知账号和密码的情况就是可以通过接口获取TOKEN，erupt内部有验证码配置，密码错误3次后会出现，防止暴力破解
