### ISSUE TITLE
非Bug，自定义按钮能否支持弹窗打开另一个 ERUPT 类的页面，有点类似与下钻。

### ISSUE THREAD

**Issue by aurthurxlc** [erupts/erupt#250]
### 版本情况

JDK版本： openjdk_8_201   
erupt版本： 1.12.12

### 功能建议

不是Bug

自定义按钮能否支持弹窗打开另一个 ERUPT 类的页面，有点类似与下钻。

**Comment by erupts** [comment]
可以用自定义按钮的自定义页面实现，自定义页面使用iframe嵌入其他erupt的页面
