### ISSUE TITLE
表格删除BUG

### ISSUE THREAD

**Issue by hply** [erupts/erupt#260]
### 版本情况

JDK版本： openjdk_8_201   
erupt版本： 1.12.14

### 问题描述（包括截图）
![image](https://github.com/user-attachments/assets/76f4d1cc-0a5b-4586-9431-2a0e51bcb23f)

bug01：表格使用时，如果选择单条进行删除操作，不使用顶部的「删除」功能按钮而是使用item右侧删除的时候，顶部的删除不会消失，而且继续「删除」功能按钮的时候，依然触发删除事件；

bug02：如果勾选item，顶部出现了删除按钮后如果此时不操作删除，而是「新增」一条数据，新增后会刷新，所有item的数据的勾选状态都消失了，然而顶部的按钮依然存在并且可以继续删除。

**Comment by erupts** [comment]
1.12.17版本已解决此问题
