### ISSUE TITLE
自定义页面中使用全局 UI 提示组件要等三秒左右才能弹出

### ISSUE THREAD

**Issue by WendelYu** [erupts/erupt#267]
### 版本情况

JDK版本： openjdk_8_201   
erupt版本： 1.12.15（请确保最新尝试是否还有问题）

### 问题描述（包括截图）
自定义页面中使用全局 UI 提示组件要等三秒左右才能弹出，这是正常的吗，还是我用错了

            recaptureData(variable) {
                // console.log(variable)
                parent.modal.info({
                    nzTitle: '确认要执行重新采集吗?',
                    nzContent: '<b style="color: red;">请确认是否执行此操作</b>',
                    nzOkText: '确定',
                    nzOkType: 'primary',
                    nzOkDanger: true,
                    nzOnOk: () => request(variable.id),
                    nzCancelText: '关闭',
                    nzOnCancel: () => console.log('Cancel')
                })
                function request(id) {
                    console.log('Request')
                    axios({
                        url: "http://" + localhostPath + '/index/reset-variable-value',
                        method: 'post',
                        params: {
                            'id': id
                        } }).then(res=>{
                        console.log("data", res.data);
                    });
                }

            },

**Comment by erupts** [comment]
未复现，进入页面后调用未发现延迟
<img width="827" alt="image" src="https://github.com/user-attachments/assets/62c55a33-f1c7-4b02-acc3-a3d0d65e7577" />
<img width="1217" alt="image" src="https://github.com/user-attachments/assets/2b2e17ab-d501-45a4-9b93-06f4475f894c" />
