### ISSUE TITLE
希望能增加Dirll的锁定joinColumn值功能

### ISSUE THREAD

**Issue by hot1976** [erupts/erupt#282]
JDK版本： openjdk_8_201   
erupt版本： 1.X.X （请确保最新尝试是否还有问题）

### 问题描述（包括截图）
Dirll可以按关系去查询出下级界面的级联数据，但如何锁定界面的级联数据呢？有时候下级界面只能在上级界面的指定行内添加数据，能否提供@LinkTree中的dependNode功能，自动锁定父界面的id。

比如某订单为id为1 ，使用Dirll维护该订单商品表，新增时，订单编码应该可以锁定为1.

**Comment by erupts** [comment]
可升级到1.12.17版本已增加linkCondition配置定义关联时的查询条件，详见：https://www.yuque.com/erupts/erupt/uk1to5#NsnOt
