### ISSUE TITLE
快速上手的Simple添加上运行报错

### ISSUE THREAD

**Issue by amtath** [erupts/erupt#4]
按找快速上手的指引，https://www.yuque.com/yuepeng/erupt/waztcb

启动后，报错
D:\studio\erupt-example\src\main\java\Simple.java:56:13
java: 找不到符号
  符号:   类 Date
  位置: 类 xyz.demo.erupt.example.model.Simple

把这一段
//时间选择
    @EruptField(
            views = @View(title = "时间"),
            edit = @Edit(title = "时间")
    )
    private Date date;
删了就ok

是哪里问题？

**Comment by erupts** [comment]
很明显，没有导入JDK提供的Date方法
