### ISSUE TITLE
批量删除的时候，如果当前页是最后一页，删除之后，会显示暂无数据，点查询按钮才能重新从第一页开始查数据

### ISSUE THREAD

**Issue by evan-guo** [erupts/erupt#43]
### 版本情况

JDK版本： openjdk_8_201   
erupt版本： 1.6.16 （请确保最新尝试是否还有问题）

### 问题描述（包括截图）
批量删除的时候，如果当前页是最后一页，删除之后，会显示暂无数据，点查询按钮才能重新从第一页开始查数据

![image](https://user-images.githubusercontent.com/52020097/121640208-38c68d00-cac0-11eb-83fc-5aba41511802.png)

![image](https://user-images.githubusercontent.com/52020097/121640248-43812200-cac0-11eb-95c7-4fec84412032.png)

![image](https://user-images.githubusercontent.com/52020097/121640272-4bd95d00-cac0-11eb-8580-ae3b5b5e06f3.png)

**Comment by erupts** [comment]
升级至1.8.5版本已针对此问题进行适配
