### ISSUE TITLE
OnToMany下，子表没有自动注入create_user_id/update_user_id/create_time/update_time

### ISSUE THREAD

**Issue by richard0913** [erupts/erupt#44]
### 版本情况

JDK版本： JDK1.8
erupt版本： 1.7.1

### 问题描述（包括截图）
主子表都继承了HyperModelVo
OneToMany模式下，
主表可以自动注入create_user_id/update_user_id/create_time/update_time
子表没有自动注入

1. 复现代码

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

**Comment by erupts** [comment]
一对多子表不会自动执行dataProxy相关函数，如有需要再主表中操作子表写入该数据
