### ISSUE TITLE
addBehavior中，对String类型下拉框赋值有效，对Integer类型下拉框赋值无效

### ISSUE THREAD

**Issue by richard0913** [erupts/erupt#45]
### 版本情况

JDK版本： JDK1.8
erupt版本： 1.7.1

### 问题描述（包括截图）
addBehavior中，对String类型下拉框赋值有效，对Integer类型下拉框赋值无效

1. 复现代码

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

**Comment by erupts** [comment]
未复现
