### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by richard0913** [erupts/erupt#46]
### 版本情况

JDK版本： JDK1.8
erupt版本： 1.7.1

### 问题描述（包括截图）
**一对多或多对多中，子表增加横向滚动条**
![1](https://user-images.githubusercontent.com/6723975/121864599-a9271580-cd2f-11eb-830e-b85a4189a436.png)

**表格列控制调整到操作区，减少空间占用，将修改后的结果保存到localStorage，每次打开页面从localStorage加载**
![2](https://user-images.githubusercontent.com/6723975/121865492-9a8d2e00-cd30-11eb-8ceb-9594ac42796e.png)

2. 堆栈信息

3. 测试涉及到的文件（注意脱密）

**Comment by erupts** [comment]
1、一对多或多对多中，子表增加横向滚动条功能在1.10.1及以上版本已支持
2、该UI需要表格组件支持，列控制localStorage加载暂不考虑加入
