### ISSUE TITLE
WEB界面添加树形结构时，点击保存会回到最上层，能不能定位在添加的位置

### ISSUE THREAD

**Issue by liufenyi** [erupts/erupt#48]
### 版本情况

JDK版本： openjdk_8_191
erupt版本： 1.7.2 

### 问题描述
以添加菜单为例，在连续添加时，非常影响效率
1. 添加一个菜单

![image](https://user-images.githubusercontent.com/81663712/122851693-ff084880-d341-11eb-90ce-7be11dff57fc.png)

2. 点击保存后，需要鼠标滚动找到添加的位置

![image](https://user-images.githubusercontent.com/81663712/122852039-8ce43380-d342-11eb-848b-251de2e048e7.png)

**Comment by erupts** [comment]
版本：1.10.1已针对此问题做出改进
