### ISSUE TITLE
菜单维护中的链接如果含有参数会被忽略

### ISSUE THREAD

**Issue by amtath** [erupts/erupt#6]
例如：添加的是
http://www.test.com:8888/Report/Server?reportlet=test.frm&op=view

跳转后，?reportlet=test.frm&op=view 会被忽略。
只跳到http://www.test.com:8888/Report/Server

**Comment by amtath** [comment]
> 例如：添加的是
> http://www.test.com:8888/Report/Server?reportlet=test.frm&op=view
> 
> 跳转后，?reportlet=test.frm&op=view 会被忽略。
> 只跳到http://www.test.com:8888/Report/Server

newwindow是正常的。link有问题

**Comment by erupts** [comment]
确实存在该问题，我尽快修复

**Comment by erupts** [comment]
已修复，详见v1.6.1
