### ISSUE TITLE
join 不能显示另一个表的IMAGE类型的图片

### ISSUE THREAD

**Issue by cfly** [erupts/erupt#60]
### 版本情况

JDK版本： openjdk_8_302  
erupt版本： 1.8.0

### 问题描述（包括截图）
![295286963C181635FE123BC0A307AEB5](https://user-images.githubusercontent.com/265776/132471966-33fb3c80-a932-4ee0-94b8-82b7e3d0416c.jpg)

join 不能显示另一个表的IMAGE类型的图片

**Comment by erupts** [comment]
bugfix version : 1.8.2
