### ISSUE TITLE
优化+建议

### ISSUE THREAD

**Issue by Specialleiliei** [erupts/erupt#72]
### 版本情况

JDK版本： openjdk_8_201   
erupt版本： 1.9.0

### 问题描述

1、直接通过界面下载按钮下载下来的表格不支持再次导入，会报错。
![image](https://user-images.githubusercontent.com/50801273/142988978-cc8de1e0-d0c5-429d-9fcd-23cdb1d048a4.png)
![image](https://user-images.githubusercontent.com/50801273/142989136-43231624-3cbe-4f6a-b57b-35e515aa4566.png)

如果想通过导出，调整数据，再次导入，却发现表格不支持岂不是很苦恼？
每次都要下载模板，再一一填数据还是比较麻烦的吧。

2、小建议：表格导入的时候能够支持数据依据指定字段覆盖，即更新，未设定则新增。

> 当然了，有需要的话自己也可以通过dataProxy来对数据进行处理。

**Comment by erupts** [comment]
模板与下载不能混用，不考虑做混用支持
