### ISSUE TITLE
如何配置此场景的列表和编辑界面？

### ISSUE THREAD

**Issue by staneee** [erupts/erupt#79]
### 问题描述

提个问题，比如有个标签表，一个商品表，

一个商品可以选择多个标签，

商品列表要显示商品关联的多个标签，这种应该怎么配置呢？

**Comment by erupts** [comment]
可以参考一对多组件：https://www.yuque.com/erupts/erupt/nevxl8

<img width="1721" alt="image" src="https://user-images.githubusercontent.com/20358088/154848664-6c29417a-a22c-4ce5-9a34-5eb64b96375b.png">
