### ISSUE TITLE
当创建的菜单的类型值重复存在的问题

### ISSUE THREAD

**Issue by ysy0407** [erupts/erupt#82]
### 版本情况

JDK版本： openjdk_8_201   
erupt版本： 1.10.1 

### 问题描述
当创建的菜单的类型值（如：都为type）为重复的时候（我只试了菜单类型为table类型），先创建一个菜单名称为A，再创建另一个菜单名称为B
先点击菜单B可会正常跳转，再点击A则依然保持在B的页面，
然后点击别的类型值不同的菜单，再点击菜单A，则依然是跳转到菜单B
应该是前端使用类型值绑定了吧？
![image](https://user-images.githubusercontent.com/33211804/155555922-7f17c5b5-db12-438b-a85c-6356f8439bee.png)

![image](https://user-images.githubusercontent.com/33211804/155550856-9009f780-fdbb-4c1a-8f58-148ce17ddbfc.png)

且在程序中获取当前菜单`eruptContextService.getCurrentEruptMenu()`时，也只能一直获取菜单B，应该是源码中如下部分导致：使用请求头中的erupt字段存储的类型值获取的时候，类型值相同时，始终为数据库中最后新增的菜单，因为map会覆盖的嘛~
```java

// xyz.erupt.upms.service.EruptUserService#cacheUserInfo
public void cacheUserInfo(EruptUser eruptUser, String token) {
        List<EruptMenu> eruptMenus = this.eruptMenuService.getUserAllMenu(eruptUser);
        Map<String, Object> valueMap = new HashMap();
        Map<String, Object> codeMap = new HashMap();
        Iterator var6 = eruptMenus.iterator();

        while(var6.hasNext()) {
            EruptMenu menu = (EruptMenu)var6.next();
            codeMap.put(menu.getCode(), menu);
            if (null != menu.getValue()) {
                valueMap.put(menu.getValue(), menu);
            }
        }

        this.sessionService.putMap("eruptAuth:menu-value-map:" + token, valueMap, (long)this.eruptUpmsConfig.getExpireTimeByLogin());
        this.sessionService.putMap("eruptAuth:menu-code-map:" + token, codeMap, (long)this.eruptUpmsConfig.getExpireTimeByLogin());
        this.sessionService.put("eruptAuth:menu-view:" + token, this.gson.toJson(this.eruptMenuService.geneMenuListVo(eruptMenus)), (long)this.eruptUpmsConfig.getExpireTimeByLogin());
    }
```
### 发现原因
本来是在1.8.3想使用`xyz.erupt.annotation.fun.DataProxy#beforeFetch`方法获取不同上级菜单（或者根据菜单的自定义参数）获取不同的数据，结果发现获取的菜单（^_^）是相同的，本来以为新版本解决了，看来还是没有的呀

**Comment by erupts** [comment]
1.10.1可以在菜单动态控制增删改查，不需要重复定义同样的菜单值
