### ISSUE TITLE
源码没有注释

### ISSUE THREAD

**Issue by dudiao** [erupts/erupt#99]
### 版本情况

JDK版本： openjdk_8_201   
erupt版本： 1.10.7 （请确保最新尝试是否还有问题）

### 问题描述（包括截图）

首先说明一下，作者整个框架的设计思路很厉害，代码写的也比我好多了，有点遗憾的是，核心源码没有注释，这对于想要贡献代码的人来说，是个门槛。

**Comment by zsf513** [comment]
确实，希望多些注释就好了

**Comment by erupts** [comment]
那部分代码的注释？

**Comment by erupts** [comment]
新功能会尽量添加详尽的注释，感谢阅读
